spring.application.name=Springboot_ecom

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

spring.app.jwtSecret=TXlTdXBlclNlY3JldEtleUZvckpXVEhTMjU2U2lnbmluZzEyMzQ1Njc4OTA=


logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.example.demoSecurity=DEBUG
