spring.application.name=Springboot_ecom

#spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
#spring.datasource.username=root
#spring.datasource.password=harman21121@30012002

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=harman21121@30012002

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.app.jwtSecret=TXlTdXBlclNlY3JldEtleUZvckpXVEhTMjU2U2lnbmluZzEyMzQ1Njc4OTA=
spring.ecom.app.jwtCookie=springbootecom

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.example.demoSecurity=DEBUG
